### ISSUE TITLE
Background image not resizing based on resolution

### ISSUE THREAD

**Issue by Edds390** [Edds390/solarnetwork-aggregated-dashboard#17]
Image not resizing:
![image](https://user-images.githubusercontent.com/21207045/37940594-01fde89a-31c6-11e8-8ff7-c754d822e460.png)

![image](https://user-images.githubusercontent.com/21207045/37940601-0a305d54-31c6-11e8-916e-c11de0ddeda3.png)

Will probably have to have rescaling logic for the image.

**Comment by KenneyC** [comment]
Fixed issue and pushed to branch : feature/homepage-aesthetics. 

Solution: Move declaration of image from css to the js file. This provides more freedom. Also added extra elements to the css file so that the image stretches according to the size of the window. Tradeoff is that the image doesn't strictly maintain it's resolution. 

Please test and close if acceptable.

**Comment by Edds390** [comment]
Fixed in [PR#15](https://github.com/Edds390/solarnetwork-aggregated-dashboard/pull/15)
