### ISSUE TITLE
Visualisation of data - graph

### ISSUE THREAD

**Issue by SeoyoungC** [Edds390/solarnetwork-aggregated-dashboard#6]
Create a carousel of graphs - each graph provides different insights into the data, such as a sum or layered comparison of values.

EDIT
Implement data parsing of JSON response from SolarNode API to be compatible with visualization data API.

**Comment by Edds390** [comment]
Basic skeleton of Nivo visualization implemented.

Basic data parser implemented.
ISSUES:

- Nivo does not intelligently set the bottom's axes' intervals:
![image](https://user-images.githubusercontent.com/21207045/37869492-5001723c-301d-11e8-83d3-d350eb44660e.png)
The problem here is that there are too many observations (number of days * number of hours).
A solution is that the tick intervals must be set by user. One method is to hardcode which datapoints have "12:00" in it so that the intervals are on a daily basis:
![image](https://user-images.githubusercontent.com/21207045/37869511-a28b6ed6-301d-11e8-857c-33db56ca06fc.png)
but this suffers from lack of robustness from other time intervals. If user wants to see e.g. month's interval of data then we will again have cluttering issues. Another solution is to map between graph witdth (in pixels) and number of observations.
Instead, we should look into another graphing library and see if it can handle the data more intelligently e.g. Dygraph.

- The data in the SolarNode API has data sources which have 'holes' in them i.e. periods where they do not record data at all. The data must thus be cleaned prior to inserting into the graph API, either by substituting with 0's or using interpolation.

**Comment by Edds390** [comment]
Nivo was a no-go.

Switched to Dygraphs.

Parsing implemented although has room for optimization.

![image](https://user-images.githubusercontent.com/21207045/37871678-2668ed5a-3050-11e8-8ce5-a37beafcef26.png)
You can zoom in by creating a horizontal window in the graph.

![image](https://user-images.githubusercontent.com/21207045/37871681-3f792dbe-3050-11e8-9d8a-3dded1de2c6f.png)
As seen above, those data sources with no recordings are left as white areas, and are interpolated.
